version: 1.41.0
commit: '%.%.%'
files:
  docker/base.dockerfile: ENV DENO_VERSION=%.%.%
  example-docker-container/Dockerfile: 'FROM denoland/deno-lambda:%.%.%'
  example-docker-container/README.md: 'FROM denoland/deno-lambda:%.%.%'
  tests/Dockerfile: ENV DENO_VERSION=%.%.%
  tests/test_bundle.json: Welcome to deno %.%.%
  tests/test_example_zip.json: Welcome to deno %.%.%
  tests/test_js.json: Welcome to deno %.%.%
  tests/test_run_deno.json: '%.%.%'
  tests/test_self_contained.json: Welcome to deno %.%.%
  tests/test_simple.json: Welcome to deno %.%.%
