#!/bin/sh
set -euo pipefail

# populate the cache from deno.land/x/lambda so we use the current files
mkdir -p .deno_dir/deps/https/deno.land/x/lambda/
cp bootstrap.ts .deno_dir/deps/https/deno.land/x/lambda/bootstrap.ts
cp mod.ts .deno_dir/deps/https/deno.land/x/lambda/mod.ts
cp runtime.ts .deno_dir/deps/https/deno.land/x/lambda/runtime.ts
# this shouldn't require a fetch to deno.land
DENO_DIR=.deno_dir ./amz-deno fetch hello.ts

# assert the required files are going to be present in the zip
ls amz-deno &> /dev/null && ls bootstrap &> /dev/null && ls hello.ts &> /dev/null

cp -R .deno_dir/gen/file/$PWD/ .deno_dir/LAMBDA_TASK_ROOT
zip -qq deno-lambda-layer.zip -x '.deno_dir/gen/file/*' -r .deno_dir amz-deno bootstrap hello.ts
zip -qq deno-lambda-example.zip -x '.deno_dir/gen/file/*' -r .deno_dir hello.ts

DENO_DIR=.deno_dir ./amz-deno bundle bundle.ts bundle.bundle.js
