#!/bin/sh
set -euo pipefail

#
# Update the version and run to update ./types.d.ts
#

# See latest version: https://www.npmjs.com/package/@types/aws-lambda
# Note: DefinitelyTyped is MIT License.
curl -fSsL https://unpkg.com/@types/aws-lambda@8.10.39/index.d.ts -o types.d.ts

deno fmt type.d.ts

python -c '
import re

txt = open("types.d.ts").read()
types = sorted(
    t[1] for t in re.findall("export (type|interface) (.*?)\s", txt)
    if "Handler" not in t[1] and "Callback" not in t[1]
)

mod = "export {\n  " + ",\n  ".join(types) + "\n} from \"./types.d.ts\";\n"
with open("mod.ts", "w") as f:
  f.write(mod)
'
deno fmt type.d.ts
