AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Deno runtime for AWS Lambda

Resources:
  DenoLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: deno
      ContentUri:
        Bucket: DENO_LAMBDA_BUCKET
        Key: deno-lambda-layer_DENO_LAMBDA_VERSION.zip
      Description: deno runtime (deno-lambda@DENO_LAMBDA_VERSION)
      LicenseInfo: MIT
      RetentionPolicy: Retain

Outputs:
  LayerArn:
    Value: !Ref DenoLambdaLayer

Metadata:
  AWS::ServerlessRepo::Application:
    Name: deno
    Description: |
      Deno runtime for AWS Lambda
    Author: Andy Hayden
    SpdxLicenseId: MIT
    Labels:
    - deno
    - layer
    - lambda
    - typescript
    HomePageUrl: https://github.com/hayd/deno-lambda
    SemanticVersion: DENO_LAMBDA_VERSION
    SourceCodeUrl: https://github.com/hayd/deno-lambda/releases/tag/DENO_LAMBDA_VERSION
