service: candidate-service
frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: provided
  stage: dev
  region: ${env:AWS_DEFAULT_REGION, 'us-east-1'}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - Fn::GetAtt: [candidatesTable, Arn]

package:
  exclude:
    - .deno_dir/gen/file
    - node_modules
    - package-lock.json

functions:
  candidateSubmission:
    handler: api/candidate.submit
    layers:
      - !GetAtt Deno.Outputs.LayerArn
    memorySize: 128
    description: Submit candidate info
    events:
      - http:
          path: candidates
          method: post

  listCandidates:
    handler: api/candidate.list
    layers:
      - !GetAtt Deno.Outputs.LayerArn
    memorySize: 128
    description: List all candidates
    events:
      - http:
          path: candidates
          method: get

  candidateDetails:
    handler: api/candidate.get
    layers:
      - !GetAtt Deno.Outputs.LayerArn
    memorySize: 128
    description: Get candidate by id
    events:
      - http:
          path: candidates/{id}
          method: get

resources:
  Transform: AWS::Serverless-2016-10-31
  Resources:
    Deno:
      Type: AWS::Serverless::Application
      Properties:
        Location:
          ApplicationId: arn:aws:serverlessrepo:us-east-1:390065572566:applications/deno
          SemanticVersion: 0.38.0

    candidatesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: candidates
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-scriptable-plugin

custom:
  scriptHooks:
    before:package:createDeploymentArtifacts: DENO_DIR=.deno_dir deno fetch api/candidate.ts && cp -R .deno_dir/gen/file/$PWD/ .deno_dir/LAMBDA_TASK_ROOT
